# ANALIZA FPL

Želim analizirati igralce v angleški Premier ligi sezoni 2020/21 in njihov vpliv v Fantasy premier ligi.

In [73]:
#IMPORT

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os


#PODATKI

pot_players = os.path.join(os.pardir, 'FPL-vaastav', 'data', '2020-21', 'cleaned_players.csv') #ne razumem zkj path ni ok -> morm dodt os.pardir
df_players = pd.read_csv(pot_players)

In [74]:
df_players

,first_name,second_name,goals_scored,assists,total_points,minutes,goals_conceded,creativity,influence,threat,bonus,bps,ict_index,clean_sheets,red_cards,yellow_cards,selected_by_percent,now_cost,element_type
0,Mesut,Özil,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.5,67,MID
1,Sokratis,Papastathopoulos,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,48,DEF
2,David,Luiz Moreira Marinho,0,0,25,886,12,30.7,132.8,88.0,0,138,24.9,3,1,1,0.7,54,DEF
3,Pierre-Emerick,Aubameyang,5,1,73,1574,16,227.2,275.2,549.0,6,208,105.0,7,0,2,6.5,113,MID
4,Cédric,Soares,0,1,23,429,4,86.3,66.6,24.0,3,88,17.7,2,0,1,0.3,46,DEF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,Andreas,Söndergaard,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.3,40,GK
663,Patrick,Cutrone,0,0,2,23,0,0.0,0.0,4.0,0,5,0.2,0,0,0,0.0,59,FWD
664,Nigel,Lonwijk,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,40,DEF
665,Willian José,Da Silva,0,1,10,258,2,22.6,21.2,81.0,0,30,12.4,1,0,0,0.2,70,FWD
666,Hugo,Bueno,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,40,DEF

Prvo izločimo vse neaktivne in premalo aktivne igralce. Tiste, ki so v letošnji sezon igrali manj kot 700 minut in osegli manj kot 40 točk. In dodamo še dodatni polji eff_time, ki pove število doseženih točk na 100 min in eff_price število doseženih točk na milijon. <br>

Spodnja tabela prikazuje 30 igralcev, z največ doseženimi točkami.

In [80]:
df_players.loc[:, 'eff_time'] = (df_players.total_points / df_players.minutes) * 100
df_players.loc[:, 'eff_price'] = (df_players.total_points / df_players.now_cost) * 10
df_aktivni = df_players.loc[(df_players.minutes > 700) & (df_players.total_points > 40)]
df_aktivni.sort_values('total_points', ascending = False).head(30)

,first_name,second_name,goals_scored,assists,total_points,minutes,goals_conceded,creativity,influence,threat,...,ict_index,clean_sheets,red_cards,yellow_cards,selected_by_percent,now_cost,element_type,efficiency,eff_time,eff_price
404,Bruno Miguel,Borges Fernandes,13,11,169,1925,25,994.7,907.4,817.0,...,272.1,8,0,4,59.2,115,MID,8.779221,8.779221,14.695652
536,Heung-Min,Son,13,6,155,1886,16,569.4,710.0,698.0,...,198.1,9,0,0,54.9,96,MID,8.218452,8.218452,16.145833
339,Mohamed,Salah,16,4,155,1831,28,507.7,731.6,1070.0,...,230.9,5,0,0,43.9,127,MID,8.465319,8.465319,12.204724
534,Harry,Kane,13,11,151,1744,17,397.7,803.6,856.0,...,205.5,7,0,1,19.8,110,FWD,8.658257,8.658257,13.727273
302,Patrick,Bamford,12,8,130,1875,36,194.5,569.4,1039.0,...,180.1,7,0,1,50.1,67,FWD,6.933333,6.933333,19.402985
43,Jack,Grealish,6,12,127,1887,24,949.3,665.4,863.0,...,247.6,11,0,5,40.4,78,MID,6.730260,6.730260,16.282051
211,Dominic,Calvert-Lewin,13,5,120,1763,26,186.4,561.2,970.0,...,171.5,5,0,3,43.2,77,FWD,6.806580,6.806580,15.584416
270,Jamie,Vardy,11,8,117,1505,19,185.6,528.8,770.0,...,148.5,6,0,1,14.3,100,FWD,7.774086,7.774086,11.700000
457,Callum,Wilson,10,6,116,1812,31,217.1,479.2,653.0,...,134.7,5,0,2,20.6,67,FWD,6.401766,6.401766,17.313433
33,Emiliano,Martínez,0,0,116,1890,24,20.0,576.0,0.0,...,59.4,11,0,0,35.0,52,GK,6.137566,6.137566,22.307692
368,Raheem,Sterling,8,6,113,1618,12,363.3,485.6,926.0,...,177.4,10,0,1,12.4,116,MID,6.983931,6.983931,9.741379
408,Marcus,Rashford,8,7,112,1855,27,387.2,529.8,738.0,...,165.6,7,0,3,12.5,96,MID,6.037736,6.037736,11.666667
605,Aaron,Cresswell,0,8,106,2070,28,546.2,442.4,67.0,...,105.9,8,0,1,24.8,57,DEF,5.120773,5.120773,18.596491
618,Tomas,Soucek,8,1,106,2070,28,129.4,582.0,667.0,...,137.9,8,1,3,18.1,54,MID,5.120773,5.120773,19.629630
336,Sadio,Mané,7,7,105,1689,20,473.6,489.2,983.0,...,194.9,5,0,2,5.6,119,MID,6.216696,6.216696,8.823529
363,Ilkay,Gündogan,9,1,104,1305,4,426.5,501.4,409.0,...,133.8,10,0,0,24.8,60,MID,7.969349,7.969349,17.333333
181,Wilfried,Zaha,9,3,102,1667,30,260.1,416.8,700.0,...,137.8,4,0,4,10.8,71,MID,6.118776,6.118776,14.366197
277,James,Maddison,6,7,102,1471,17,606.1,451.0,445.0,...,150.0,9,0,4,16.5,74,MID,6.934058,6.934058,13.783784
121,Nick,Pope,0,0,102,1890,24,10.0,634.2,0.0,...,64.4,7,0,0,13.7,55,GK,5.396825,5.396825,18.545455
284,James,Justin,2,2,101,2070,25,290.7,472.2,195.0,...,96.0,9,0,4,30.2,52,DEF,4.879227,4.879227,19.423077
280,Harvey,Barnes,7,3,100,1714,21,283.2,435.6,718.0,...,143.8,7,0,0,7.8,69,MID,5.834306,5.834306,14.492754
61,Ollie,Watkins,10,4,100,1890,24,344.6,514.6,1058.0,...,191.1,11,0,1,19.3,64,FWD,5.291005,5.291005,15.625000
646,Pedro,Lomba Neto,4,6,99,1888,28,760.2,462.0,542.0,...,176.6,7,0,1,7.0,57,MID,5.243644,5.243644,17.368421
504,James,Ward-Prowse,5,5,98,1980,37,602.2,566.6,155.0,...,132.2,8,0,4,7.9,60,MID,4.949495,4.949495,16.333333
385,Rúben Santos,Gato Alves Dias,0,1,98,1779,8,34.9,385.2,164.0,...,58.6,13,0,3,22.7,61,DEF,5.508713,5.508713,16.065574
263,Kasper,Schmeichel,0,0,96,2070,25,0.0,536.6,0.0,...,53.7,9,0,0,10.3,55,GK,4.637681,4.637681,17.454545
300,Stuart,Dallas,4,3,95,1970,37,270.3,470.6,315.0,...,105.8,7,0,4,14.4,48,DEF,4.822335,4.822335,19.791667
364,Kevin,De Bruyne,3,10,95,1405,11,796.8,514.6,663.0,...,197.6,9,0,1,10.3,118,MID,6.761566,6.761566,8.050847
303,Jack,Harrison,6,4,95,1755,34,522.8,485.2,396.0,...,140.6,7,0,2,2.2,54,MID,5.413105,5.413105,17.592593
370,Ederson,Santana de Moraes,0,0,95,1890,13,0.0,296.0,0.0,...,29.7,13,0,2,8.6,61,GK,5.026455,5.026455,15.573770

Pogledamo povprečne vrednosti igralcev po pozicijah:
* DEF - obrambni igralci 
* FWD - napadalni igralci
* GK - golmani
* MID - vezni igralci

V spodnji tabeli so izpuščeni stolpci, ki so glede na pozicije očitni ali nas ne zanimajo (goals, assists, goals_conceded, selected, minutes, selected_by_percent, yellow_cards, red_cards)

In [90]:
df_aktivni.groupby('element_type')[['total_points', 'minutes','bonus', 'bps', 'ict_index', 'now_cost','eff_time', 'eff_price']].mean()

,total_points,minutes,bonus,bps,ict_index,now_cost,eff_time,eff_price
element_type,,,,,,,,
DEF,66.307692,1567.276923,5.676923,325.338462,65.304615,50.953846,4.317128,13.024396
FWD,75.035714,1337.535714,9.392857,250.321429,111.214286,72.071429,5.574839,10.475062
GK,79.750000,1873.300000,6.950000,385.600000,47.735000,50.800000,4.274999,15.668694
MID,70.300000,1486.712500,5.750000,272.800000,101.441250,62.950000,4.784037,11.277358

In [77]:
df_aktivni.groupby('element_type').count()

,first_name,second_name,goals_scored,assists,total_points,minutes,goals_conceded,creativity,influence,threat,bonus,bps,ict_index,clean_sheets,red_cards,yellow_cards,selected_by_percent,now_cost,efficiency
element_type,,,,,,,,,,,,,,,,,,,
DEF,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65
FWD,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28
GK,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20
MID,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80