# ANALIZA PODATKOV FPL IGRALCEV

In [3]:
#IMPORT
import pandas as pd
import numpy as py
import os.path

#PODATKI
pot_under = os.path.join('FPL-vaastav', 'data', '2020-21', 'understat', 'understat_player.csv')
pot_clear = os.path.join("FPL-vaastav", "data", "2020-21", "cleaned_players.csv")

df_under = pd.read_csv(pot_under)
df_cplayer = pd.read_csv(pot_clear)

Okrajšave:
    xG/A - expected goals/assists
    npg - non penalty goals
    xGChain - Total team-adjusted xGoals earned by the team on possessions in which the player participated
    xGBuildup - 
    ICT - influence, creativity, threat - statistika, po kateri FPL dodeljuje bonus pike

In [7]:
df_under

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,453,Son Heung-Min,6,477,8,3.058989,2,1.725785,14,15,0,0,F M,Tottenham,8,3.058989,5.234103,1.964930
1,5555,Dominic Calvert-Lewin,6,523,7,5.044698,0,0.106039,20,1,1,0,F,Everton,7,5.044698,4.703016,1.158628
2,755,Jamie Vardy,5,383,6,4.540889,0,0.162430,9,2,0,0,F S,Leicester,2,1.496214,1.875315,0.216671
3,822,Patrick Bamford,6,496,6,2.577310,1,0.354126,23,4,1,0,F,Leeds,6,2.577310,3.628449,1.042374
4,1250,Mohamed Salah,6,540,6,4.242469,0,1.922533,29,17,0,0,F,Liverpool,4,2.720132,6.302794,2.369689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,8961,Rúben Dias,3,270,0,0.084903,0,0.000000,1,0,1,0,D,Manchester City,0,0.084903,0.964187,0.964187
393,8965,Vladimir Coufal,3,270,0,0.102352,1,0.199398,1,3,2,0,D,West Ham,0,0.102352,0.593137,0.401146
394,8966,Filip Krovinovic,3,196,0,0.086533,0,0.000000,3,0,0,0,M S,West Bromwich Albion,0,0.086533,0.279004,0.231620
395,8992,Hakim Ziyech,2,24,0,0.000000,0,0.107196,0,1,0,0,S,Chelsea,0,0.000000,0.000000,0.000000
396,9040,Conor Gallagher,2,180,0,0.052440,0,0.101213,2,2,0,0,M,West Bromwich Albion,0,0.052440,0.135786,0.092833

In [9]:
df_cplayer

,first_name,second_name,goals_scored,assists,total_points,minutes,goals_conceded,creativity,influence,threat,bonus,bps,ict_index,clean_sheets,red_cards,yellow_cards,selected_by_percent,now_cost,element_type
0,Mesut,Özil,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.7,68,MID
1,Sokratis,Papastathopoulos,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,49,DEF
2,David,Luiz Moreira Marinho,0,0,7,319,5,9.8,66.6,21.0,0,51,9.7,0,0,0,1.1,55,DEF
3,Pierre-Emerick,Aubameyang,1,1,20,540,7,103.1,93.4,117.0,0,73,31.4,1,0,1,15.3,117,MID
4,Cédric,Soares,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.2,47,DEF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,Ki-Jana,Hoever,0,0,2,29,1,15.2,13.8,2.0,0,9,3.1,0,0,0,0.0,45,DEF
586,Nélson,Cabral Semedo,0,0,15,329,4,41.4,54.0,28.0,0,72,12.4,2,0,0,2.3,55,DEF
587,Meritan,Shabani,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,45,MID
588,Rayan,Ait Nouri,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,50,DEF
589,Owen,Otasowie,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,45,MID